### ISSUE TITLE
Add a JavaScript style guide to the frontend-toolkit

### ISSUE THREAD

**Issue by seanh** [hypothesis/frontend-toolkit#49]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

Add a JavaScript style guide to <https://github.com/hypothesis/frontend-toolkit>. And an eslint config for ES6, the airbnb-base config might be a good starting point.

**Comment by robertknight** [comment]
Some status updates from the Brighton meetup in January 2019: https://docs.google.com/presentation/d/1U4-3ONkJREzNTAULPdNrc4238x2LyyjswAd6RTSO8oM/edit#slide=id.g4b02c14b59_0_5

We're going to adopt automated code formatting with Prettier for the client which obsoletes some elements of a style guide. Other elements will still need to be specified.

**Comment by robertknight** [comment]
> We're going to adopt automated code formatting with Prettier for the client which obsoletes some elements of a style guide. 

This has been done for all projects. We do have a guide at https://github.com/hypothesis/frontend-toolkit/blob/main/docs/js-guide.md but it needs to be updated to reflect the change away from using JSDoc for types to instead using native TypeScript syntax.

**Comment by acelaya** [comment]
> > We're going to adopt automated code formatting with Prettier for the client which obsoletes some elements of a style guide.
> 
> This has been done for all projects. We do have a guide at https://github.com/hypothesis/frontend-toolkit/blob/main/docs/js-guide.md but it needs to be updated to reflect the change away from using JSDoc for types to instead using native TypeScript syntax.

Completed by https://github.com/hypothesis/frontend-toolkit/pull/56
